### PR TITLE
Some English fixes.

### PR DESCRIPTION
**Pull request by chikamichi**
Petites corrections/propositions sur le README.

### CODE REVIEW

**Comment by jeromeetienne** [comment]
looks good. thanks :)

**Comment by chikamichi** [comment]
I forgot about the js highlighting in two remaining code blocks, though. Anyway :)

**Comment by jeromeetienne** [comment]
i dont understand what you mean

**Comment by chikamichi** [comment]
This:

``` js
var highlighted = true;
function(err, callback) { doSomething('funky'); }
```

Using github's enhanced mardown markup.

**Comment by jeromeetienne** [comment]
got it. made the change https://github.com/jeromeetienne/gowiththeflow.js/commit/aa7e208bc80c7f5b17bdbdf1fedbf2b2b367e032

**Pull request merged**
